global:
  scrape_interval: 15s

scrape_configs:
  # - job_name: 'jupyterlab'
  #   static_configs:
  #     - targets: ['host.docker.internal:8888']
  #   metrics_path: /metrics
  #   params:
  #     token: [ "06ce6e71123ed846b20bab4a8f9cdcd72b8d7653fd2efb35" ]
  - job_name: 'jupyterlab-python'
    static_configs:
      - targets: ['host.docker.internal:8001']