name: "Step 2: Publish Release 1"
on:
  workflow_run:
    workflows: ["Step 1: Prep Release"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      branch:
        description: "The target branch"
        required: false
      release_url:
        description: "The URL of the draft GitHub release"
        required: false
      steps_to_skip:
        description: "Comma separated list of steps to skip"
        required: false
        default: "npm"

jobs:
  publish_release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Debug APP_ID
        run: |
          echo "APP_ID: ${{ vars.APP_ID }}"
      - name: Debug APP_PRIVATE_KEY
        run: |
          echo "APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}"
      
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      
      - name: Check Token Generation
        run: |
          if [ -z "${{ steps.app-token.outputs.token }}" ]; then
            echo "Error: Token generation failed."
            exit 1
          else
            echo "Token generated successfully."
          fi
      
      - name: Check release URL
        run: |
          echo "Release URL: ${{ github.event.inputs.release_url }}"

      - name: Populate Release
        id: populate-release
        uses: jupyter-server/jupyter_releaser/.github/actions/populate-release@v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          branch: ${{ github.event.inputs.branch }}
          release_url: ${{ github.event.inputs.release_url }}
          steps_to_skip: ${{ github.event.inputs.steps_to_skip }}

      - name: Finalize Release
        id: finalize-release
        env:
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        uses: jupyter-server/jupyter_releaser/.github/actions/finalize-release@v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          release_url: ${{ steps.populate-release.outputs.release_url }}

      - name: "** Next Step **"
        if: ${{ success() }}
        run: |
          echo "Verify the final release"
          echo ${{ steps.finalize-release.outputs.release_url }}

      - name: "** Failure Message **"
        if: ${{ failure() }}
        run: |
          echo "Failed to Publish the Draft Release Url:"
          echo ${{ steps.populate-release.outputs.release_url }}
permissions:
  attestations: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  id-token: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  security-events: write
  statuses: write